# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instascrapy-configs.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfiguracoesWindow(object):
    def setupUi(self, ConfiguracoesWindow):
        ConfiguracoesWindow.setObjectName("ConfiguracoesWindow")
        ConfiguracoesWindow.resize(650, 700)
        ConfiguracoesWindow.setMinimumSize(QtCore.QSize(650, 700))
        ConfiguracoesWindow.setMaximumSize(QtCore.QSize(650, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icone/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ConfiguracoesWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ConfiguracoesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.body = QtWidgets.QFrame(self.centralwidget)
        self.body.setStyleSheet("")
        self.body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName("body")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.body)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.conteudo = QtWidgets.QFrame(self.body)
        self.conteudo.setMaximumSize(QtCore.QSize(650, 700))
        self.conteudo.setStyleSheet("QFrame{\n"
"    background-color: rgb(30,30,30);\n"
"    border-radius: 10px;\n"
"}")
        self.conteudo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.conteudo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.conteudo.setObjectName("conteudo")
        self.logo_2 = QtWidgets.QFrame(self.conteudo)
        self.logo_2.setGeometry(QtCore.QRect(183, 40, 283, 89))
        self.logo_2.setMinimumSize(QtCore.QSize(283, 89))
        self.logo_2.setMaximumSize(QtCore.QSize(283, 89))
        self.logo_2.setStyleSheet("background-image: url(:/logo/logo.png);\n"
"backroung-repeat: no-repeat;\n"
"background-position: center;\n"
"border-radius: 6px;")
        self.logo_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_2.setObjectName("logo_2")
        self.input_user = QtWidgets.QLineEdit(self.conteudo)
        self.input_user.setGeometry(QtCore.QRect(135, 220, 380, 50))
        self.input_user.setMinimumSize(QtCore.QSize(380, 50))
        self.input_user.setMaximumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.input_user.setFont(font)
        self.input_user.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(105,105,105);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(65,65,65);\n"
"    color: rgb(120,120,120)\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(85,85,85);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(0, 255, 252);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.input_user.setText("")
        self.input_user.setMaxLength(32)
        self.input_user.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_user.setObjectName("input_user")
        self.btn_atualizar = QtWidgets.QPushButton(self.conteudo)
        self.btn_atualizar.setGeometry(QtCore.QRect(305, 600, 210, 45))
        self.btn_atualizar.setMaximumSize(QtCore.QSize(280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_atualizar.setFont(font)
        self.btn_atualizar.setStyleSheet("QPushButton{\n"
"    background-color:  rgb(80,80,80);\n"
"    border: 2px solid rgb(70,70,70);\n"
"    border-radius: 5px;\n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(100,100,100);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(27, 107, 106);\n"
"    border: 2px solid rgb(0, 255, 252);\n"
"}")
        self.btn_atualizar.setObjectName("btn_atualizar")
        self.lb_description = QtWidgets.QLabel(self.conteudo)
        self.lb_description.setGeometry(QtCore.QRect(170, 190, 310, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setItalic(False)
        self.lb_description.setFont(font)
        self.lb_description.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_description.setStyleSheet("color :rgb(120,120,120)")
        self.lb_description.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_description.setObjectName("lb_description")
        self.lb_configs = QtWidgets.QLabel(self.conteudo)
        self.lb_configs.setGeometry(QtCore.QRect(205, 140, 240, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.lb_configs.setFont(font)
        self.lb_configs.setStyleSheet("color: rgb(255, 255, 255);")
        self.lb_configs.setObjectName("lb_configs")
        self.btn_cancelar = QtWidgets.QPushButton(self.conteudo)
        self.btn_cancelar.setGeometry(QtCore.QRect(135, 600, 160, 45))
        self.btn_cancelar.setMaximumSize(QtCore.QSize(280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_cancelar.setFont(font)
        self.btn_cancelar.setStyleSheet("QPushButton{\n"
"    background-color:  rgb(80,80,80);\n"
"    border: 2px solid rgb(70,70,70);\n"
"    border-radius: 5px;\n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(100,100,100);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(27, 107, 106);\n"
"    border: 2px solid rgb(0, 255, 252);\n"
"}")
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.input_password = QtWidgets.QLineEdit(self.conteudo)
        self.input_password.setGeometry(QtCore.QRect(135, 280, 380, 50))
        self.input_password.setMinimumSize(QtCore.QSize(380, 50))
        self.input_password.setMaximumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.input_password.setFont(font)
        self.input_password.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(105,105,105);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(65,65,65);\n"
"    color: rgb(120,120,120)\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(85,85,85);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(0, 255, 252);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.input_password.setText("")
        self.input_password.setMaxLength(32)
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password.setObjectName("input_password")
        self.input_sheetid = QtWidgets.QLineEdit(self.conteudo)
        self.input_sheetid.setGeometry(QtCore.QRect(135, 450, 380, 50))
        self.input_sheetid.setMinimumSize(QtCore.QSize(380, 50))
        self.input_sheetid.setMaximumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.input_sheetid.setFont(font)
        self.input_sheetid.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(105,105,105);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(65,65,65);\n"
"    color: rgb(120,120,120)\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(85,85,85);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(0, 255, 252);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.input_sheetid.setText("")
        self.input_sheetid.setMaxLength(32)
        self.input_sheetid.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_sheetid.setObjectName("input_sheetid")
        self.input_aba_sheets = QtWidgets.QLineEdit(self.conteudo)
        self.input_aba_sheets.setGeometry(QtCore.QRect(135, 510, 380, 50))
        self.input_aba_sheets.setMinimumSize(QtCore.QSize(380, 50))
        self.input_aba_sheets.setMaximumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.input_aba_sheets.setFont(font)
        self.input_aba_sheets.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(105,105,105);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(65,65,65);\n"
"    color: rgb(120,120,120)\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(85,85,85);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(0, 255, 252);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.input_aba_sheets.setText("")
        self.input_aba_sheets.setMaxLength(32)
        self.input_aba_sheets.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_aba_sheets.setObjectName("input_aba_sheets")
        self.lb_google_sheets = QtWidgets.QLabel(self.conteudo)
        self.lb_google_sheets.setGeometry(QtCore.QRect(270, 410, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setItalic(False)
        self.lb_google_sheets.setFont(font)
        self.lb_google_sheets.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_google_sheets.setStyleSheet("color :rgb(120,120,120)")
        self.lb_google_sheets.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_google_sheets.setObjectName("lb_google_sheets")
        self.input_sessionid = QtWidgets.QLineEdit(self.conteudo)
        self.input_sessionid.setGeometry(QtCore.QRect(135, 340, 380, 50))
        self.input_sessionid.setMinimumSize(QtCore.QSize(380, 50))
        self.input_sessionid.setMaximumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.input_sessionid.setFont(font)
        self.input_sessionid.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(105,105,105);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(65,65,65);\n"
"    color: rgb(120,120,120)\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(85,85,85);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(0, 255, 252);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.input_sessionid.setText("")
        self.input_sessionid.setMaxLength(32)
        self.input_sessionid.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_sessionid.setObjectName("input_sessionid")
        self.horizontalLayout_4.addWidget(self.conteudo)
        self.verticalLayout.addWidget(self.body)
        ConfiguracoesWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ConfiguracoesWindow)
        QtCore.QMetaObject.connectSlotsByName(ConfiguracoesWindow)

    def retranslateUi(self, ConfiguracoesWindow):
        _translate = QtCore.QCoreApplication.translate
        ConfiguracoesWindow.setWindowTitle(_translate("ConfiguracoesWindow", "Configurações"))
        self.input_user.setPlaceholderText(_translate("ConfiguracoesWindow", "USER"))
        self.btn_atualizar.setText(_translate("ConfiguracoesWindow", "ATUALIZAR"))
        self.lb_description.setText(_translate("ConfiguracoesWindow", "Estás configurações é um arquivo dentro da pasta!"))
        self.lb_configs.setText(_translate("ConfiguracoesWindow", "Configurações"))
        self.btn_cancelar.setText(_translate("ConfiguracoesWindow", "CANCELAR"))
        self.input_password.setPlaceholderText(_translate("ConfiguracoesWindow", "SENHA"))
        self.input_sheetid.setPlaceholderText(_translate("ConfiguracoesWindow", "ID DA PLANILHA DO GOOGLE SHEETS"))
        self.input_aba_sheets.setPlaceholderText(_translate("ConfiguracoesWindow", "PÁGINA DO GOOGLE SHEETS"))
        self.lb_google_sheets.setText(_translate("ConfiguracoesWindow", "GOOGLE SHEETS"))
        self.input_sessionid.setPlaceholderText(_translate("ConfiguracoesWindow", "ID DE SESSÃO (COOKIE)"))
import file_rc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConfiguracoesWindow = QtWidgets.QMainWindow()
    ui = Ui_ConfiguracoesWindow()
    ui.setupUi(ConfiguracoesWindow)
    ConfiguracoesWindow.show()
    sys.exit(app.exec_())
